services:
  [CONTAINER]:
    image: [IMAGE-URL]:latest
    container_name: [CONTAINER]
    volumes:
      - ./serviceOpts.dockerDir/[CONTAINER]/config:/container/path
    ports:
      - [HOST-PORT]:[CONTAINER-PORT]
    networks:
      - swag_default #if proxied
    restart: unless-stopped

networks:
  swag_default:
    external: true
