# Auto-generated using compose2nix v0.3.2-pre.
{ pkgs, lib, serviceOpts, uptix, ... }:

{

  # Containers
  virtualisation.oci-containers.containers."silverbullet" = {
    image = uptix.dockerImage "zefhemel/silverbullet";
    volumes = [
      "${serviceOpts.dockerDir}/silverbullet/data:/space:rw"
    ];
    log-driver = "journald";
    extraOptions = [
      "--network-alias=silverbullet"
      "--network=proxynet"
    ];
    environmentFiles = [
      "/run/secrets/selfhosting/silverbullet/env"
    ];
  };
  systemd.services."docker-silverbullet" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
      RestartMaxDelaySec = lib.mkOverride 90 "1m";
      RestartSec = lib.mkOverride 90 "100ms";
      RestartSteps = lib.mkOverride 90 9;
    };
    partOf = [
      "docker-compose-silverbullet-root.target"
    ];
    wantedBy = [
      "docker-compose-silverbullet-root.target"
    ];
  };

  # Root service
  # When started, this will automatically create all resources and start
  # the containers. When stopped, this will teardown all resources.
  systemd.targets."docker-compose-silverbullet-root" = {
    unitConfig = {
      Description = "Root target generated by compose2nix.";
    };
    wantedBy = [ "multi-user.target" ];
  };
}
