keys:
  - &users: 
    - &ryan age1y7c90y378epp3l6gpsyqaaawzhp8c8eegdj8cn6af58sgvxj7f7skwm02n
  - &hosts:
    - &nixbook age1g5tk5d9sdykgt0xcyujaxtpsv2a3zt6r73ud60rxkfjraw2wvc3sc3df4z
creation_rules:
  - path_regex: secrets/secrets.yaml$
    key_groups:
      - age:
        - *ryan
        - *nixbook
