services:
  app:
    image: ghcr.io/plankanban/planka:latest
    restart: on-failure
    volumes:
      - /serviceOpts.dockerDir/planka/favicons:/app/public/favicons
      - /serviceOpts.dockerDir/planka/user-avatars:/app/public/user-avatars
      - /serviceOpts/dockerDir/planka/background-images:/app/public/background-images
      - /serviceOpts/dockerDir/planka/attachments:/app/private/attachments
    # Optionally override this to your user/group
    # user: 1000:100
    environment:
      - BASE_URL=https://projects.secrets.selfhosting.domain
      - DATABASE_URL=postgresql://postgres@postgres/planka

      #- SECRET_KEY=sops
      - LOG_LEVEL=warn

      - TRUST_PROXY=true
      # - TOKEN_EXPIRES_IN=365 # In days

      # Configure knex to accept SSL certificates
      # - KNEX_REJECT_UNAUTHORIZED_SSL_CERTIFICATE=false

      # - SHOW_DETAILED_AUTH_ERRORS=false

    ports:
      - 3001:1337
    networks:
      - proxynet 
      - default 
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: postgres:16-alpine
    restart: on-failure
    volumes:
      - /serviceOpts.dockerDir/planka/db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=planka
      - POSTGRES_HOST_AUTH_METHOD=trust
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d planka"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  proxynet:
    external: true
