# Auto-generated using compose2nix v0.3.2-pre.
{
  pkgs,
  lib,
  serviceOpts,
  config,
  ...
}: {
  # Containers
  virtualisation.oci-containers.containers."uptime-kuma" = {
    image = "louislam/uptime-kuma:1";
    volumes = [
      "${serviceOpts.dockerDir}/uptime-kuma/config:/app/data:rw"
    ];
    ports = [
      "3001:3001/tcp"
    ];
    user = config.users.users.${serviceOpts.dockerUser}.uid;
    log-driver = "journald";
    extraOptions = [
      "--network-alias=uptime-kuma"
      #"dns=10.10.1.1"
      "--network=swag_default"
    ];
  };
  systemd.services."podman-uptime-kuma" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
    };
    partOf = [
      "podman-compose-uptime-kuma-root.target"
    ];
    wantedBy = [
      "podman-compose-uptime-kuma-root.target"
    ];
  };

  # Root service
  # When started, this will automatically create all resources and start
  # the containers. When stopped, this will teardown all resources.
  systemd.targets."podman-compose-uptime-kuma-root" = {
    unitConfig = {
      Description = "Root target generated by compose2nix.";
    };
    wantedBy = ["multi-user.target"];
  };
}
