services:
  open-webui:
    image: ghcr.io/open-webui/open-webui:latest
    container_name: open-webui
    volumes:
      - /config.serviceOpts.dockerDir/open-webui:/app/backend/data
    environment:
      - 'OLLAMA_BASE_URL=http://10.10.1.17:11434'
    networks:
      - proxynet
    restart: unless-stopped

networks:
  proxynet:
    external: true
