# Auto-generated using compose2nix v0.3.3-pre.
{
  config,
  uptix,
  lib,
  ...
}: {
  # Containers
  virtualisation.oci-containers.containers."lubelogger" = {
    image = uptix.dockerImage "ghcr.io/hargata/lubelogger:latest";
    volumes = [
      "${config.serviceOpts.dockerDir}/lubelogger/data:/App/data:rw"
      "${config.serviceOpts.dockerDir}/lubelogger/keys:/root/.aspnet/DataProtection-Keys:rw"
    ];
    log-driver = "journald";
    extraOptions = [
      "--network-alias=app"
      "--network=proxynet"
    ];
  };
  systemd.services."docker-lubelogger" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
      RestartMaxDelaySec = lib.mkOverride 90 "1m";
      RestartSec = lib.mkOverride 90 "100ms";
      RestartSteps = lib.mkOverride 90 9;
    };
    partOf = [
      "docker-compose-lubelogger-root.target"
    ];
    wantedBy = [
      "docker-compose-lubelogger-root.target"
    ];
  };

  # Root service
  # When started, this will automatically create all resources and start
  # the containers. When stopped, this will teardown all resources.
  systemd.targets."docker-compose-lubelogger-root" = {
    unitConfig = {
      Description = "Root target generated by compose2nix.";
    };
    wantedBy = ["multi-user.target"];
  };
}
