# Auto-generated using compose2nix v0.3.2-pre.
{
  lib,
  config,
  secrets,
  uptix,
  ...
}: {
  # Containers
  virtualisation.oci-containers.containers."vaultwarden" = {
    image = uptix.dockerImage "vaultwarden/server";
    environment = {
      "INVITATIONS_ALLOWED" = "true";
      "LOG_FILE" = "/data/vaultwarden.log";
      "SERVER_ADMIN_EMAIL" = "${secrets.personal-mail.address}";
      "SIGNUPS_ALLOWED" = "false";
      "WEBSOCKET_ENABLED" = "true";
    };
    volumes = [
      "${config.serviceOpts.dockerDir}/vaultwarden/config:/data:rw"
    ];
    log-driver = "journald";
    extraOptions = [
      "--network-alias=vaultwarden"
      "--network=proxynet"
    ];
  };
  systemd.services."docker-vaultwarden" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "no";
    };
    partOf = [
      "docker-compose-vaultwarden-root.target"
    ];
    wantedBy = [
      "docker-compose-vaultwarden-root.target"
    ];
  };

  # Root service
  # When started, this will automatically create all resources and start
  # the containers. When stopped, this will teardown all resources.
  systemd.targets."docker-compose-vaultwarden-root" = {
    unitConfig = {
      Description = "Root target generated by compose2nix.";
    };
    wantedBy = ["multi-user.target"];
  };
}
