# Auto-generated using compose2nix v0.3.2-pre.
{
  pkgs,
  lib,
  serviceOpts,
  systemOpts,
  uptix,
  ...
}: {
  # Containers
  virtualisation.oci-containers.containers."speedtest-tracker" = {
    image = uptix.dockerImage "lscr.io/linuxserver/speedtest-tracker";
    environment = {
      "DB_CONNECTION" = "sqlite";
      "PGID" = "100";
      "PRUNE_RESULTS_OLDER_THAN" = "365";
      "PUID" = "1000";
      "SPEEDTEST_SCHEDULE" = "0 */6 * * *";
      "TZ" = "${systemOpts.timezone}";
    };
    volumes = [
      "${serviceOpts.dockerDir}/speedtest-tracker/config:/config:rw"
    ];
    log-driver = "journald";
    extraOptions = [
      "--network-alias=speedtest-tracker"
      "--network=proxynet"
    ];
  };
  systemd.services."docker-speedtest-tracker" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "no";
    };
    partOf = [
      "docker-compose-speedtest-tracker-root.target"
    ];
    wantedBy = [
      "docker-compose-speedtest-tracker-root.target"
    ];
  };

  # Root service
  # When started, this will automatically create all resources and start
  # the containers. When stopped, this will teardown all resources.
  systemd.targets."docker-compose-speedtest-tracker-root" = {
    unitConfig = {
      Description = "Root target generated by compose2nix.";
    };
    wantedBy = ["multi-user.target"];
  };
}
