services:
    speedtest-tracker:
        image: lscr.io/linuxserver/speedtest-tracker
        container_name: speedtest-tracker
        networks:
          - proxynet
        environment:
            - DB_CONNECTION=sqlite
            - TZ=config.time.timeZone
            - PUID=1000
            - PGID=100
            - 'SPEEDTEST_SCHEDULE=0 */6 * * *'
            - PRUNE_RESULTS_OLDER_THAN=365
        volumes:
            - '/serviceOpts.dockerDir/speedtest-tracker/config:/config:rw'
        
networks:
  proxynet:
    external: true
