# Auto-generated using compose2nix v0.3.2-pre.
{
  pkgs,
  lib,
  config,
  uptix,
  ...
}: {
  # Containers
  virtualisation.oci-containers.containers."duplicati" = {
    image = uptix.dockerImage "lscr.io/linuxserver/duplicati:latest";
    environment = {
      "PGID" = "0";
      "PUID" = "0";
      "TZ" = config.time.timeZone;
    };
    volumes = [
      "/:/source:rw"
      "/mnt/storage/backups:/backups:rw"
      "${config.serviceOpts.dockerDir}/duplicati/config:/config:rw"
    ];
    log-driver = "journald";
    extraOptions = [
      "--network-alias=duplicati"
      "--network=proxynet"
    ];
    environmentFiles = [
      config.sops.secrets."selfhosting/duplicati/env".path
    ];
  };
  systemd.services."docker-duplicati" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
      RestartMaxDelaySec = lib.mkOverride 90 "1m";
      RestartSec = lib.mkOverride 90 "100ms";
      RestartSteps = lib.mkOverride 90 9;
    };
    after = [
      "docker-network-duplicati_default.service"
    ];
    requires = [
      "docker-network-duplicati_default.service"
    ];
    partOf = [
      "docker-compose-duplicati-root.target"
    ];
    wantedBy = [
      "docker-compose-duplicati-root.target"
    ];
  };

  # Networks
  systemd.services."docker-network-duplicati_default" = {
    path = [pkgs.docker];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
      ExecStop = "docker network rm -f duplicati_default";
    };
    script = ''
      docker network inspect duplicati_default || docker network create duplicati_default
    '';
    partOf = ["docker-compose-duplicati-root.target"];
    wantedBy = ["docker-compose-duplicati-root.target"];
  };

  # Root service
  # When started, this will automatically create all resources and start
  # the containers. When stopped, this will teardown all resources.
  systemd.targets."docker-compose-duplicati-root" = {
    unitConfig = {
      Description = "Root target generated by compose2nix.";
    };
    wantedBy = ["multi-user.target"];
  };
}
