# Auto-generated using compose2nix v0.3.2-pre.
{
  pkgs,
  lib,
  serviceOpts,
  uptix,
  ...
}: {
  # Containers
  virtualisation.oci-containers.containers."actualserver" = {
    image = uptix.dockerImage "actualbudget/actual-server:latest";
    volumes = [
      "${serviceOpts.dockerDir}/actualserver/config:/data:rw"
    ];
    log-driver = "journald";
    extraOptions = [
      "--network=proxynet"
    ];
  };
  systemd.services."docker-actualserver" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "no";
    };
    partOf = [
      "docker-compose-actual-root.target"
    ];
    wantedBy = [
      "docker-compose-actual-root.target"
    ];
  };

  # Root service
  # When started, this will automatically create all resources and start
  # the containers. When stopped, this will teardown all resources.
  systemd.targets."docker-compose-actual-root" = {
    unitConfig = {
      Description = "Root target generated by compose2nix.";
    };
    wantedBy = ["multi-user.target"];
  };
}
