services:
  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - /serviceOpts.dockerDir/jellyfin/library:/config
      - /mnt/storage/media/tvshows:/data/tvshows
      - /mnt/storage/media/movies:/data/movies
      #    ports:
      #      - 8096:8096
      #      - 8920:8920 #optional
      #      - 7359:7359/udp #optional
      #      - 1900:1900/udp #optional
    networks: 
      - proxynet
    restart: unless-stopped

networks:
  proxynet:
    external: true
