services:
  dms:
    image: ghcr.io/docker-mailserver/docker-mailserver:latest
    container_name: dms
    # Provide the FQDN of your mail server here (Your DNS MX record should point to this value)
    hostname: secrets.admin-mail.host
    env_file: environment.env
    # More information about the mail-server ports:
    # https://docker-mailserver.github.io/docker-mailserver/latest/config/security/understanding-the-ports/
    # To avoid conflicts with yaml base-60 float, DO NOT remove the quotation marks.
    ports:
      - "25:25"    # SMTP  (explicit TLS => STARTTLS)
      - "143:143"  # IMAP4 (explicit TLS => STAR
      - "465:465"  # ESMTP (implicit TLS)
      - "587:587"  # ESMTP (explicit TLS => STARTTLS)
      - "993:993"  # IMAP4 (implicit TLS)
    volumes:
      - /serviceOpts.dockerDir/dms/mail-data/:/var/mail/
      - /serviceOpts.dockerDir/dms/mail-state/:/var/mail-state/
      - /serviceOpts.dockerDir/dms/mail-logs/:/var/log/mail/
      - /serviceOpts.dockerDir/dms/config/:/tmp/docker-mailserver/
      - /etc/localtime:/etc/localtime:ro
      - /serviceOpts.dockerDir/swag/config/etc/letsencrypt/:/etc/letsencrypt/:ro
    restart: unless-stopped
    stop_grace_period: 1m
    # Uncomment if using `ENABLE_FAIL2BAN=1`:
    cap_add:
      - NET_ADMIN
    healthcheck:
      test: "ss --listening --tcp | grep -P 'LISTEN.+:smtp' || exit 1"
      timeout: 3s
      retries: 0
