---
services:
  swag:
    image: lscr.io/linuxserver/swag:latest
    container_name: swag
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=$$timezone
      - URL=$$domain
      - VALIDATION=dns
      - SUBDOMAINS=wildcard #optional
      - DNSPLUGIN=cloudflare #optional
      - PROPAGATION= #optional
      - EMAIL=$$email
      - ONLY_SUBDOMAINS=true #optional
      - STAGING=false #optional
      - DOCKER_MODS=linuxserver/mods:swag-auto-reload
    volumes:
      - ./config:/config
    ports:
      - 443:443
    restart: unless-stopped
    dns:
      - 10.10.1.1
    user: ryan
