# in docker-compose.nix, add a reference to the secret env files for
# mysql passwords and jwt secrets:
# In app config:
# 
#   environmentFiles = [
#     "/run/secrets/selfhosting/vikunja/env-app"
#   ];
# In db config:
# 
#   environmentFiles = [
#     "/run/secrets/selfhosting/vikunja/env-app"
#   ];

services:
  app:
    image: vikunja/vikunja
    environment:
      VIKUNJA_SERVICE_PUBLICURL: https://todo.secrets.selfhosting.domain
      VIKUNJA_DATABASE_HOST: db
      #VIKUNJA_DATABASE_PASSWORD: config.sops.secrets."vikunja/dbPass"
      VIKUNJA_DATABASE_TYPE: mysql
      VIKUNJA_DATABASE_USER: vikunja
      VIKUNJA_DATABASE_DATABASE: vikunja
      #VIKUNJA_SERVICE_JWTSECRET: config.sops.secrets."vikunja/jwtSecret"
      #    ports:
      #- 3456:3456
    volumes:
      - /serviceOpts.dockerDir/vikunja/config:/app/vikunja/files
    networks:
      - proxynet
      - default
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped
  db:
    image: lscr.io/linuxserver/mariadb:latest
    #    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      PGID: 100
      PUID: 1000
      #MYSQL_ROOT_PASSWORD
      MYSQL_USER: vikunja
      #MYSQL_PASSWORD
      MYSQL_DATABASE: vikunja
    volumes:
      - /serviceOpts.dockerDir/vikunja/db:/config
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -u $$MYSQL_USER --password=$$MYSQL_PASSWORD"]
      interval: 2s
      start_period: 30s

networks:
  proxynet:
    external: true
