---
services:
  swag:
    image: lscr.io/linuxserver/swag:latest
    container_name: swag
    networks:
      - proxynet
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=$$timezone
      - URL=$$domain
      - VALIDATION=dns
      - SUBDOMAINS=wildcard #optional
      - DNSPLUGIN=cloudflare #optional
      - PROPAGATION= #optional
      - EMAIL=$$email
      - ONLY_SUBDOMAINS=true #optional
      - STAGING=false #optional
      - DOCKER_MODS=linuxserver/mods:swag-auto-reload|linuxserver/mods:swag-dashboard
    volumes:
      - ./config:/config
      - ./proxy-confs:/config/nginx/proxy-confs
    ports:
      - 443:443
    restart: unless-stopped

networks:
  proxynet:
    external: true
