services:
  vaultwarden:
    image: uptix.dockerImage vaultwarden/server
    container_name: vaultwarden
    environment:
        - TZ=America/New_York
        - HOST_OS=Nixos
        - HOST_HOSTNAME=testvm
        - HOST_CONTAINERNAME=vaultwarden
        - TCP_PORT_80=8080
        - SERVER_ADMIN_EMAIL=[ADMINMAIL]
        - SIGNUPS_ALLOWED=true
        - INVITATIONS_ALLOWED=true
        - WEBSOCKET_ENA
    volumes:
      - ./serviceOpts.dockerDir/vaultwarden/config:/data
    networks:
      - swag_default 
    restart: unless-stopped

networks:
  swag_default:
    external: true
