# Auto-generated using compose2nix v0.3.2-pre.
{
  pkgs,
  lib,
  serviceOpts,
  uptix,
  ...
}: {
  # Containers
  virtualisation.oci-containers.containers."albyhub" = {
    image = uptix.dockerImage "ghcr.io/getalby/hub:latest";
    environment = {
      "LOG_EVENTS" = "true";
      "WORK_DIR" = "/data/albyhub";
    };
    volumes = [
      "${serviceOpts.dockerDir}/albyhub/config:/data/albyhub:rw"
    ];
    log-driver = "journald";
    extraOptions = [
      "--network-alias=albyhub"
      "--network=proxynet"
    ];
  };
  systemd.services."docker-albyhub" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "no";
    };
    partOf = [
      "docker-compose-albyhub-root.target"
    ];
    wantedBy = [
      "docker-compose-albyhub-root.target"
    ];
  };

  # Root service
  # When started, this will automatically create all resources and start
  # the containers. When stopped, this will teardown all resources.
  systemd.targets."docker-compose-albyhub-root" = {
    unitConfig = {
      Description = "Root target generated by compose2nix.";
    };
    wantedBy = ["multi-user.target"];
  };
}
